spring.application.name=AIChatBot
server.port=8080

ollama.base-url=http://localhost:11434
ollama.model=llama3.2:3b
ollama.powerful.model=qwen3.5:latest
jwt.secret.key=cVajIL2z1dmENjSY4GxFyAx4PJ5IW2tsUIzuSRrEiuM=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/aichatbot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Sankethisapro@908
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
