spring.application.name=AIChatBot
server.port=8080


spring.ai.azure.openai.endpoint=https://YOUR-RESOURCE-NAME.openai.azure.com/
spring.ai.azure.openai.api-key=YOUR_API_KEY
spring.ai.azure.openai.chat.options.deployment-name=YOUR_DEPLOYMENT_NAME